export const countryCodes = [
    { code: "+355", country: "Albania" },
    { code: "+376", country: "Andorra" },
    { code: "+374", country: "Armenia" },
    { code: "+43", country: "Austria" },
    { code: "+375", country: "Belarus" },
    { code: "+32", country: "Belgium" },
    { code: "+387", country: "Bosnia and Herzegovina" },
    { code: "+359", country: "Bulgaria" },
    { code: "+385", country: "Croatia" },
    { code: "+357", country: "Cyprus" },
    { code: "+420", country: "Czech Republic" },
    { code: "+45", country: "Denmark" },
    { code: "+372", country: "Estonia" },
    { code: "+358", country: "Finland" },
    { code: "+33", country: "France" },
    { code: "+49", country: "Germany" },
    { code: "+30", country: "Greece" },
    { code: "+36", country: "Hungary" },
    { code: "+354", country: "Iceland" },
    { code: "+353", country: "Ireland" },
    { code: "+39", country: "Italy" },
    { code: "+371", country: "Latvia" },
    { code: "+423", country: "Liechtenstein" },
    { code: "+370", country: "Lithuania" },
    { code: "+352", country: "Luxembourg" },
    { code: "+389", country: "North Macedonia" },
    { code: "+356", country: "Malta" },
    { code: "+373", country: "Moldova" },
    { code: "+377", country: "Monaco" },
    { code: "+382", country: "Montenegro" },
    { code: "+31", country: "Netherlands" },
    { code: "+47", country: "Norway" },
    { code: "+48", country: "Poland" },
    { code: "+351", country: "Portugal" },
    { code: "+40", country: "Romania" },
    { code: "+7", country: "Russia" },
    { code: "+378", country: "San Marino" },
    { code: "+381", country: "Serbia" },
    { code: "+421", country: "Slovakia" },
    { code: "+386", country: "Slovenia" },
    { code: "+34", country: "Spain" },
    { code: "+46", country: "Sweden" },
    { code: "+41", country: "Switzerland" },
    { code: "+380", country: "Ukraine" },
    { code: "+44", country: "United Kingdom" },
    { code: "+379", country: "Vatican City" },
  ];
  
  export const difficulties = [
    { label: 'Easy', value: 'easy', color: 'green.500' },
    { label: 'Medium', value: 'medium', color: 'yellow.500' },
    { label: 'Hard', value: 'hard', color: 'red.500' },
  ];
  
  